language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial   
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS

addons:
  artifacts:
    paths:
      - $(ls ./dist/* | tr "\n" ":")

env:
 global:
  - secure: "mFbe5pAGVHen7Gi43/i/AKUzNr0O9TmLY7p1HChLaPDJ/WTSuVhx1P/naNEgjivxuoLAX0tFcdxSQK0xhlZfo2NNkDPN9AiwMkD3FS1rV533ev3eY9qVisfV3esP7vvL9lTPP9hsVv80K6MuTwqkhEsY9mHIGQCTs+sXX5d941fOufP82r3NViXKTIwlE3diYq3OUOhJ43FetMUR8QavZGNep+Kn/u2duPbMlVZeUZksFHx5ooZUEunxOKuntl7cAK+PbYJ7iGQIYNYCkgNHGYrNf2JugS+JwA2zqD/n5uQgX24ox/mNvR24YFOdW8IELnI926gyqlJcvI19FpUAA4bX8lPxB3qgZ3/xRw3rqtWAWakpBqAMAFNNVWqcyTxyYk641UQUZ67ftjTEuasTgmmpzmg8f6OT1yczFyZMXcQUpsNCui2bgmlgOknEnVWVB4F+8ZfoEElmIudMO/fc0sniyBB4FOmyz+wfjIiwXhX0Fqt8PCbe+2lQJNVGKJxnqma0+lMQHyewUcvzps3Kn9T35eTC9ZyUxbkbr/AnNHT742WeyV6K/kPMspgqCnHV1TUoinNI/PvxSkp9N/ovJIFPNLa22pg/ST4qUm+YHP1XcwSHJR/3U8h3OjH3iuoJfW3qnI0pIFLay/HUPE/DcT1hEkw9IX6DIpmH48fTt/M="
  - secure: "akMP3fu42uCXvBH8IvaWzxHCKvFttGE9ABHdOMxtOosc5S1RiAb2qansonFkXdKGM6JpWnDpukEt1jNX/O4uSjIIrhkWEF8Ds0zzy5IuzRr6XcHSBbJwcASWT1McPyEY2goZYX4H0sz3qZCM92X8VVWNsy5r8CNu1Ux4BY4F2HErIQkw08owOsacqJikk9bdy2vn88oBlrvkVAB8buffBO38eXVLutYj8J3p/VlzBx0ukZeToFV17B8DUx2Bn2V4DfVlXC3y4h0xjri3jsx+uM70cVCvd0LfkN+hOU6yrn9ogIRMj7JFfXpxhqZSss144pLuM5k9RXL0j8qZjZUBueL6KV8ZNAr+bebKi2ft2hj9HCGtyvXGS6xbi1vBj0u9ow2KeTKBXtmu2gD2rEV+PeihZNyKaLkgt5A+UW4EbgrFNau0nJT0jfgaWyZgtYEtDS7nVB8il/e1PfwwDxppWn7GiPK9SONRyfE4FdGdPTmUN049H+ydg8C5OXqKw1ajSuQgEmOQ+QH4S1TQN+G0mU0PDTv5K3NdFzlqsoTZU63v7i8E8xquQ9/AI4zVP4SuZxSlMEdEaCyvm/PP7Z3tniCMdu5+bDAeaPZQeAhjTOomdG2HSmDZhvqmIsJbcAjJBqxwzAENllwcRcntApYWn4jwgpzSWK+xt2GJCBh6x3U="
  - secure: "cxOi5SaAvcd80ptx/yGIat5WSzagwpji9Pp5HElaXySaEGpBs39N6c8KVvQf5Um0lkzm9xWCiWMCt2ncICovrEIB8E7DXfUl4B9OpUmmcFHuZffv1yAkYB1hyIGNmJKy2tassbPq6rx8Ov+eJGfVq/27F6ryxCa6tKtzwsswswkXvQZXg1FTU88t8bhBxs0ye1UgK8JkVDScgJrI02QjQjekpIUxwhkM0dqJ9lM6gLRMgbb4zFMERxuNY35oEBmams0k6xDwKcDfNOCA0HvrWayWgx72rTg7y0X3mPhkO2BMgUDl3vKDnCrPcG7vRML/ENNn0XQegZ4Jin35jEBJDbbnjQkx7JVX6JzdVlZwmYWfi1qCpqk8nsWxTvs6EZEud0ejgCl51I7/jtLlQGEuiYSuelG8aev3DHbRbkhJlFs76LuSc5887DBAja9MTHv+OSZSM/FhqwHEOmBHIvbEvA1fcAj5VflMkXb7mk1dLmjcFIgL/i3U2rvyfHBHfzNJuVEkPECG1a1oqb1WUJje/Nx/PAL1pigSiQpWp9gNMZHMKdQklQSOBXK1WBJn9CwYCaFIK1PTz7sanL3BGGyyffVNBXcW3HKKB6L65pvZxK/mk746jAilistncRksg2JjYcfoDznPVoJwpSCGeUUEZSKTQtMAxK/sWL+rtA424yI="

install:
  - pip3 install --upgrade pip
  - pip3 install -r dev-requirements.txt
  - python3 --version

script:
  - bash ./build.sh
  
before_deploy:
  - export FILE_TO_UPLOAD=$(ls dist/*)

deploy:
  provider: releases
  api_key:
    - secure: "hJaO3097yKJPRF4+7D45PPmo9nLXncp/MTCA5/+sRlQ1vC2LY4f84AsIU85fh2v1M2awvbnL5VEWfohIRarF2XrD5P8ge8om0F0rPLc8R+vCOFzOQccutxAbk4xFAJS+2OIjOgPwzJqxa8dVG74RsSskWjruDykYTMXJJO5XSva6UUoEaZtKy1nJJABJtgwFvlbaEHOyrbvOAVs7MOcZJ6keRfKSa02jxwt+mWZion3fNQIuUZJOJO77k84ruTWgf9uHxiSxHX/MxWe+KQc/A8IV7HApq4cNpq3Z50GRMuNCzdM1CRURZq3nGnb1RkGX0Mw7cqJbo0YaRksGp0pG4EH2uVWyBBUtuoUoWVK9UnWHA++s1soMOd6tAXF4Da95UsNAfj3X7hrvUR5wDT1SlMxL88o/KpW5GJyiP9+U6Tpanh+bmASOo1eDfhl8aQajmI7RUEoe+QS1a3Kw9VUnOkupa33rucQ31fDjRj5gqhCoM2kx6Kl+SjivV7HR9XxVAwC4wjwOdMLIX6reUEC65XpUzy6q1Din1rThtzldg5F8mwm2U2emqe+gP1Xnz3BEWbCn6HH0ZCo/abWsotgQydT0twyJi6IP3gOMCGcHYH6rayXsu8giDwsrCWBcZ2nVKYPJoLvCa6/Bydzg8DW3ltIcJA4Q+IJ0wdwMdhjcpAI="
  file_glob: true
  file: "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  draft: true
  on:
    tags: true
