language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial   
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS

addons:
  artifacts:
    paths:
      - $(ls ./dist/* | tr "\n" ":")

install:
  - pip3 install --upgrade pip
  - pip3 install -r dev-requirements.txt
  - pip3 install -r requirements.txt
  - python3 --version

script:
  - bash ./build.sh
  
before_deploy:
  - export FILE_TO_UPLOAD=$(ls dist/* | tr "\n" ":")

deploy:
  provider: releases
  api_key:
    - secure: "hJaO3097yKJPRF4+7D45PPmo9nLXncp/MTCA5/+sRlQ1vC2LY4f84AsIU85fh2v1M2awvbnL5VEWfohIRarF2XrD5P8ge8om0F0rPLc8R+vCOFzOQccutxAbk4xFAJS+2OIjOgPwzJqxa8dVG74RsSskWjruDykYTMXJJO5XSva6UUoEaZtKy1nJJABJtgwFvlbaEHOyrbvOAVs7MOcZJ6keRfKSa02jxwt+mWZion3fNQIuUZJOJO77k84ruTWgf9uHxiSxHX/MxWe+KQc/A8IV7HApq4cNpq3Z50GRMuNCzdM1CRURZq3nGnb1RkGX0Mw7cqJbo0YaRksGp0pG4EH2uVWyBBUtuoUoWVK9UnWHA++s1soMOd6tAXF4Da95UsNAfj3X7hrvUR5wDT1SlMxL88o/KpW5GJyiP9+U6Tpanh+bmASOo1eDfhl8aQajmI7RUEoe+QS1a3Kw9VUnOkupa33rucQ31fDjRj5gqhCoM2kx6Kl+SjivV7HR9XxVAwC4wjwOdMLIX6reUEC65XpUzy6q1Din1rThtzldg5F8mwm2U2emqe+gP1Xnz3BEWbCn6HH0ZCo/abWsotgQydT0twyJi6IP3gOMCGcHYH6rayXsu8giDwsrCWBcZ2nVKYPJoLvCa6/Bydzg8DW3ltIcJA4Q+IJ0wdwMdhjcpAI="
  file_glob: true
  file: "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  draft: true
  on:
    tags: true
